"""schema_improvements_category_softdelete_session_link

Revision ID: 01c7b4519155
Revises: 9b854bad1e9d
Create Date: 2026-02-06 19:07:39.866154

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '01c7b4519155'
down_revision: Union[str, Sequence[str], None] = '9b854bad1e9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'categories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('display_order', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.add_column('foods', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('foods', sa.Column('is_out_of_stock', sa.Boolean(), nullable=True))
    op.add_column('foods', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_foods_category'), table_name='foods')
    op.create_index(
        op.f('ix_foods_category_id'), 'foods', ['category_id'], unique=False
    )
    op.create_foreign_key(
        None, 'foods', 'categories', ['category_id'], ['id'], ondelete='SET NULL'
    )
    op.drop_column('foods', 'category')
    op.add_column('orders', sa.Column('table_session_id', sa.Integer(), nullable=True))
    op.add_column(
        'orders', sa.Column('payment_status', sa.String(length=20), nullable=True)
    )
    op.create_index(
        op.f('ix_orders_payment_status'), 'orders', ['payment_status'], unique=False
    )
    op.create_index(
        op.f('ix_orders_table_session_id'), 'orders', ['table_session_id'], unique=False
    )
    op.create_foreign_key(
        None,
        'orders',
        'table_sessions',
        ['table_session_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.add_column('tables', sa.Column('qr_token', sa.String(length=100), nullable=True))
    op.add_column('tables', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tables_qr_token'), 'tables', ['qr_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tables_qr_token'), table_name='tables')
    op.drop_column('tables', 'deleted_at')
    op.drop_column('tables', 'qr_token')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_table_session_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_status'), table_name='orders')
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'table_session_id')
    op.add_column(
        'foods',
        sa.Column(
            'category', sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, 'foods', type_='foreignkey')
    op.drop_index(op.f('ix_foods_category_id'), table_name='foods')
    op.create_index(op.f('ix_foods_category'), 'foods', ['category'], unique=False)
    op.drop_column('foods', 'deleted_at')
    op.drop_column('foods', 'is_out_of_stock')
    op.drop_column('foods', 'category_id')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
