"""add image_url to foods

Revision ID: 357c7c633381
Revises: c5857a32fe69
Create Date: 2026-02-02 16:15:02.520653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '357c7c633381'
down_revision: Union[str, Sequence[str], None] = 'c5857a32fe69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foods', 'image_url')
    # ### end Alembic commands ###
