"""Add qr_code_path to tables

Revision ID: 766e5ff3335f
Revises: 20da996ff331
Create Date: 2026-02-03 11:14:40.374714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '766e5ff3335f'
down_revision: Union[str, Sequence[str], None] = '20da996ff331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('qr_code_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'qr_code_path')
    # ### end Alembic commands ###
