"""add description to foods

Revision ID: c5857a32fe69
Revises: 
Create Date: 2026-02-02 16:10:33.968814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5857a32fe69'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('tables', sa.Column('capacity', sa.Integer(), nullable=False))
    op.add_column('tables', sa.Column('is_occupied', sa.Boolean(), nullable=False))
    op.alter_column('tables', 'table_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tables', 'table_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('tables', 'is_occupied')
    op.drop_column('tables', 'capacity')
    op.drop_column('foods', 'description')
    # ### end Alembic commands ###
